// _templates/nextjs/app/core-control.tsx
"use client";

import { useEffect, useMemo, useState } from "react";
import { applyCoreState, loadCoreState, readCoreState, SuperCoreMode } from "../lib/core-mixer";
import { applyFontState, loadFontState, readFontState } from "../lib/font-mixer";
import { FONT_LIST } from "../lib/font-list";

export function CoreControl() {
  const [open, setOpen] = useState(false);
  const [mode, setMode] = useState<SuperCoreMode>("dark");
  const [base, setBase] = useState("#0a1628");
  const [surface, setSurface] = useState("#00d4aa");
  const [accent, setAccent] = useState("#00d4aa");
  const [tint, setTint] = useState("#ff6b6b");
  const [primaryFont, setPrimaryFont] = useState("Inter");
  const [secondaryFont, setSecondaryFont] = useState("Merriweather");

  const palette = useMemo(
    () => ({ base, surface, accent, tint }),
    [base, surface, accent, tint]
  );

  useEffect(() => {
    const coreState = loadCoreState(readCoreState());
    setMode(coreState.mode);
    setBase(coreState.colors.base);
    setSurface(coreState.colors.surface);
    setAccent(coreState.colors.accent);
    setTint(coreState.colors.tint);

    const fontState = loadFontState(readFontState());
    setPrimaryFont(fontState.primary);
    setSecondaryFont(fontState.secondary);
  }, []);

  const saveToMemory = () => {
    const core = applyCoreState({ mode, colors: palette });
    const fonts = applyFontState({ primary: primaryFont, secondary: secondaryFont });
    console.log("[core-control] saved to memory", {
      keys: { core: "sc:coreState", fonts: "sc:fontState" },
      core,
      fonts
    });
  };

  const loadFromMemory = () => {
    const core = loadCoreState(readCoreState());
    const fonts = loadFontState(readFontState());
    setMode(core.mode);
    setBase(core.colors.base);
    setSurface(core.colors.surface);
    setAccent(core.colors.accent);
    setTint(core.colors.tint);
    setPrimaryFont(fonts.primary);
    setSecondaryFont(fonts.secondary);
    console.log("[core-control] loaded from memory", {
      keys: { core: "sc:coreState", fonts: "sc:fontState" },
      core,
      fonts
    });
  };

  const applyMode = (nextMode: SuperCoreMode) => {
    const core = applyCoreState({ mode: nextMode });
    setMode(core.mode);
  };

  const applyColor = (key: keyof typeof palette, value: string) => {
    const core = applyCoreState({ colors: { [key]: value } });
    setMode(core.mode);
    setBase(core.colors.base);
    setSurface(core.colors.surface);
    setAccent(core.colors.accent);
    setTint(core.colors.tint);
  };

  const applyFonts = (nextPrimary: string, nextSecondary: string) => {
    const fonts = applyFontState({ primary: nextPrimary, secondary: nextSecondary });
    setPrimaryFont(fonts.primary);
    setSecondaryFont(fonts.secondary);
  };

  return (
    <div className={`tc-wrap ${open ? "open" : ""}`}>
      <div className="tc-panel">
        <div className="tc-section">
          <p className="tc-label">Mode</p>
          <div className="tc-row">
            <button className={`tc-mode-btn ${mode === "dark" ? "active" : ""}`} type="button" onClick={() => applyMode("dark")}>Dark</button>
            <button className={`tc-mode-btn ${mode === "light" ? "active" : ""}`} type="button" onClick={() => applyMode("light")}>Light</button>
          </div>
        </div>

        <div className="tc-section">
          <p className="tc-label">Colors</p>
          <label className="tc-color-row"><input className="tc-swatch" type="color" value={base} onChange={(e) => applyColor("base", e.target.value)} /><span>Base</span></label>
          <label className="tc-color-row"><input className="tc-swatch" type="color" value={surface} onChange={(e) => applyColor("surface", e.target.value)} /><span>Surface</span></label>
          <label className="tc-color-row"><input className="tc-swatch" type="color" value={accent} onChange={(e) => applyColor("accent", e.target.value)} /><span>Accent</span></label>
          <label className="tc-color-row"><input className="tc-swatch" type="color" value={tint} onChange={(e) => applyColor("tint", e.target.value)} /><span>Tint</span></label>
        </div>

        <div className="tc-section">
          <label className="tc-label" htmlFor="sc-primary-font">Primary Font</label>
          <select id="sc-primary-font" className="tc-select" value={primaryFont} onChange={(e) => applyFonts(e.target.value, secondaryFont)}>
            {FONT_LIST.map((font) => <option key={font.value} value={font.value}>{font.label}</option>)}
          </select>
        </div>

        <div className="tc-section">
          <label className="tc-label" htmlFor="sc-secondary-font">Secondary Font</label>
          <select id="sc-secondary-font" className="tc-select" value={secondaryFont} onChange={(e) => applyFonts(primaryFont, e.target.value)}>
            {FONT_LIST.map((font) => <option key={font.value} value={font.value}>{font.label}</option>)}
          </select>
        </div>

        <div className="tc-memory-row">
          <button className="tc-sync-btn" type="button" onClick={saveToMemory}>Save</button>
          <button className="tc-sync-btn" type="button" onClick={loadFromMemory}>Load</button>
        </div>
      </div>

      <button className="tc-fab" type="button" title="Theme controls" aria-label="Theme controls" aria-expanded={open} onClick={() => setOpen((v) => !v)}>
        <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <circle cx="13.5" cy="6.5" r=".5" fill="currentColor"></circle>
          <circle cx="17.5" cy="10.5" r=".5" fill="currentColor"></circle>
          <circle cx="8.5" cy="7.5" r=".5" fill="currentColor"></circle>
          <circle cx="6.5" cy="12.5" r=".5" fill="currentColor"></circle>
          <path d="M12 2C6.5 2 2 6.5 2 12s4.5 10 10 10c.926 0 1.648-.746 1.648-1.688 0-.437-.18-.835-.437-1.125-.29-.289-.438-.652-.438-1.125a1.64 1.64 0 0 1 1.668-1.668h1.996c3.051 0 5.555-2.503 5.555-5.554C21.965 6.012 17.461 2 12 2z"></path>
        </svg>
      </button>
    </div>
  );
}

// _templates/angular/src/app/components/core-control/core-control.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  applyCoreColors,
  applyCoreMode,
  applyCoreState,
  loadCoreState,
  readCoreState,
  SuperCoreColors,
  SuperCoreMode,
} from '../../theme/core-mixer';
import { applyFontState, loadFontState, readFontState, FontState } from '../../theme/font-mixer';
import { FONT_LIST, FontOption } from '../../theme/font-list';

@Component({
  selector: 'app-core-control',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './core-control.component.html',
  styleUrl: './core-control.component.inline.css',
})
export class CoreControlComponent {
  open = false;

  colorMode: SuperCoreMode = 'dark';
  baseColor    = '#0a1628';
  surfaceColor = '#00d4aa';
  accentColor  = '#00d4aa';
  tintColor    = '#ff6b6b';

  primaryFont   = 'Inter';
  secondaryFont = 'Merriweather';
  fonts: FontOption[] = FONT_LIST;

  constructor() {
    this.syncStoredState();
  }

  toggle() { this.open = !this.open; }

  syncStoredState() {
    this.loadFromMemory();
  }

  saveToMemory() {
    const coreState = applyCoreState({
      mode: this.colorMode,
      colors: {
        base: this.baseColor,
        surface: this.surfaceColor,
        accent: this.accentColor,
        tint: this.tintColor,
      },
    });
    const fontState = applyFontState({
      primary: this.primaryFont,
      secondary: this.secondaryFont,
    });

    this.syncColors(coreState);
    this.syncFonts(fontState);

    fetch('http://localhost:3001/theme', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ core: coreState, fonts: fontState }),
    }).catch(() => {});

    console.log('[core-control] saved to memory', {
      keys: { core: 'sc:coreState', fonts: 'sc:fontState' },
      core: coreState,
      fonts: fontState,
    });
  }

  loadFromMemory() {
    fetch('http://localhost:3001/theme')
      .then(r => r.json())
      .then(state => {
        if (state.core)  this.syncColors(applyCoreState(state.core));
        if (state.fonts) this.syncFonts(applyFontState(state.fonts));
        console.log('[core-control] loaded from server', state);
      })
      .catch(() => {
        try {
          const coreState = loadCoreState(readCoreState());
          this.syncColors(coreState);
        } catch {}
        try {
          const fontState = loadFontState(readFontState());
          this.syncFonts(fontState);
        } catch {}
        console.log('[core-control] loaded from localStorage (server unavailable)');
      });
  }

  setMode(mode: SuperCoreMode)  { this.syncColors(applyCoreMode(mode)); }
  setBase(e: Event)             { this.syncColors(applyCoreColors({ base:    (e.target as HTMLInputElement).value })); }
  setSurface(e: Event)          { this.syncColors(applyCoreColors({ surface: (e.target as HTMLInputElement).value })); }
  setAccent(e: Event)           { this.syncColors(applyCoreColors({ accent:  (e.target as HTMLInputElement).value })); }
  setTint(e: Event)             { this.syncColors(applyCoreColors({ tint:    (e.target as HTMLInputElement).value })); }

  setPrimaryFont(e: Event) {
    this.syncFonts(applyFontState({ primary: (e.target as HTMLSelectElement).value, secondary: this.secondaryFont }));
  }
  setSecondaryFont(e: Event) {
    this.syncFonts(applyFontState({ primary: this.primaryFont, secondary: (e.target as HTMLSelectElement).value }));
  }

  private syncColors(state: { mode: SuperCoreMode; colors: SuperCoreColors }) {
    this.colorMode    = state.mode;
    this.baseColor    = state.colors.base;
    this.surfaceColor = state.colors.surface;
    this.accentColor  = state.colors.accent;
    this.tintColor    = state.colors.tint;
  }

  private syncFonts(state: FontState) {
    this.primaryFont   = state.primary;
    this.secondaryFont = state.secondary;
  }
}

<div class="tc-wrap" [class.open]="open">

  <div class="tc-panel">

    <div class="tc-section">
      <p class="tc-label">Mode</p>
      <div class="tc-row">
        <button class="tc-mode-btn" [class.active]="colorMode === 'dark'"  (click)="setMode('dark')">Dark</button>
        <button class="tc-mode-btn" [class.active]="colorMode === 'light'" (click)="setMode('light')">Light</button>
      </div>
    </div>

    <div class="tc-section">
      <p class="tc-label">Colors</p>
      <label class="tc-color-row">
        <input type="color" [value]="baseColor"    (input)="setBase($event)"    class="tc-swatch">
        <span>Base</span>
      </label>
      <label class="tc-color-row">
        <input type="color" [value]="surfaceColor" (input)="setSurface($event)" class="tc-swatch">
        <span>Surface</span>
      </label>
      <label class="tc-color-row">
        <input type="color" [value]="accentColor"  (input)="setAccent($event)"  class="tc-swatch">
        <span>Accent</span>
      </label>
      <label class="tc-color-row">
        <input type="color" [value]="tintColor"    (input)="setTint($event)"    class="tc-swatch">
        <span>Tint</span>
      </label>
    </div>

    <div class="tc-section">
      <p class="tc-label">Primary Font</p>
      <select class="tc-select" [value]="primaryFont" (change)="setPrimaryFont($event)">
        @for (font of fonts; track font.value) {
          <option [value]="font.value">{{ font.label }}</option>
        }
      </select>
    </div>

    <div class="tc-section">
      <p class="tc-label">Secondary Font</p>
      <select class="tc-select" [value]="secondaryFont" (change)="setSecondaryFont($event)">
        @for (font of fonts; track font.value) {
          <option [value]="font.value">{{ font.label }}</option>
        }
      </select>
    </div>

    <div class="tc-memory-row">
      <button class="tc-sync-btn" type="button" (click)="saveToMemory()">Save</button>
      <button class="tc-sync-btn" type="button" (click)="loadFromMemory()">Load</button>
    </div>

  </div>

  <button class="tc-fab" (click)="toggle()" title="Theme controls">
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
      <circle cx="13.5" cy="6.5" r=".5" fill="currentColor"/>
      <circle cx="17.5" cy="10.5" r=".5" fill="currentColor"/>
      <circle cx="8.5" cy="7.5" r=".5" fill="currentColor"/>
      <circle cx="6.5" cy="12.5" r=".5" fill="currentColor"/>
      <path d="M12 2C6.5 2 2 6.5 2 12s4.5 10 10 10c.926 0 1.648-.746 1.648-1.688 0-.437-.18-.835-.437-1.125-.29-.289-.438-.652-.438-1.125a1.64 1.64 0 0 1 1.668-1.668h1.996c3.051 0 5.555-2.503 5.555-5.554C21.965 6.012 17.461 2 12 2z"/>
    </svg>
  </button>

</div>
